wip client pool 200/500
TODO

2025-06-10T20:28:04.308+02:00 ERROR 21116 --- [study-server] [io-5001-exec-18] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.io.ManagedHttpClientConnection.isConsistent()" because "conn" is null] with root cause
java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.io.ManagedHttpClientConnection.isConsistent()" because "conn" is null
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.release(PoolingHttpClientConnectionManager.java:412) ~[httpclient5-5.3.jar!/:5.3]
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.discardEndpoint(InternalExecRuntime.java:246) ~[httpclient5-5.3.jar!/:5.3]
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.releaseEndpoint(InternalExecRuntime.java:260) ~[httpclient5-5.3.jar!/:5.3]
	at org.apache.hc.client5.http.impl.classic.ResponseEntityProxy.releaseConnection(ResponseEntityProxy.java:80) ~[httpclient5-5.3.jar!/:5.3]
	at org.apache.hc.client5.http.impl.classic.ResponseEntityProxy.eofDetected(ResponseEntityProxy.java:115) ~[httpclient5-5.3.jar!/:5.3]
	at org.apache.hc.core5.http.io.EofSensorInputStream.checkEOF(EofSensorInputStream.java:199) ~[httpcore5-5.2.5.jar!/:5.2.5]
	at org.apache.hc.core5.http.io.EofSensorInputStream.read(EofSensorInputStream.java:136) ~[httpcore5-5.2.5.jar!/:5.2.5]
	at java.base/java.io.InputStream.readNBytes(InputStream.java:412) ~[na:na]
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:349) ~[na:na]
	at org.springframework.util.FileCopyUtils.copyToByteArray(FileCopyUtils.java:149) ~[spring-core-6.1.12.jar!/:6.1.12]
	at org.springframework.web.client.DefaultResponseErrorHandler.getResponseBody(DefaultResponseErrorHandler.java:234) ~[spring-web-6.1.12.jar!/:6.1.12]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:177) ~[spring-web-6.1.12.jar!/:6.1.12]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.1.12.jar!/:6.1.12]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.1.12.jar!/:6.1.12]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942) ~[spring-web-6.1.12.jar!/:6.1.12]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891) ~[spring-web-6.1.12.jar!/:6.1.12]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790) ~[spring-web-6.1.12.jar!/:6.1.12]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:507) ~[spring-web-6.1.12.jar!/:6.1.12]
	at org.gridsuite.study.server.service.NetworkMapService.getElementsInfos(NetworkMapService.java:76) ~[!/:na]
	at org.gridsuite.study.server.service.StudyService.getNetworkElementsInfos(StudyService.java:789) ~[!/:na]