springboot 3.4.9 (#860)
* Add TestChannelBinderConfiguration to all test contexts where it was missing

This makes the tests pass. The test would not pass because messages were missing
which resulted in:
[ERROR]   LoadFlowTest.testGetLimitViolations:482->createNetworkModificationNode:1048 expected: not <null>
This error would only happen depending on the order of the test classes, so rerunning only the failed
class would pass, but running all tests would not pass.

Presumably spring cloud stream changed how it chooses to initialize, before
just by having testbinder on the classpath it disabled rabbitmq, but now it
needs to be explicit in each context. This prevents errors like

at startup:
WARN  org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer - Consumer raised exception, processing can restart if the connection factory supports it. Exception summary: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connexion refusée
INFO  org.springframework.amqp.rabbit.connection.CachingConnectionFactory - Attempting to connect to: [localhost:5672]
INFO  org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer - Broker not available; cannot force queue declarations during start: java.net.ConnectException: Connexion refusée

during the tests:
10:58:36.964 [main] ERROR org.springframework.transaction.support.TransactionSynchronizationUtils - TransactionSynchronization.afterCompletion threw exception
java.lang.RuntimeException: org.springframework.messaging.MessageHandlingException: error occurred in message handler
  at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:242)
Caused by: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connexion refusée

As said earlier the tests were affecting subsequent tests (is there some static state in spring-cloud-stream?? or maybe our contexts are wrongly shared between tests??),
this would make tests that do have the TestBinder imported explicitly in the context fail as well, they are also trying
to connect to a real rabbitmq. And these tests actually assert things using the testbinder and the assertions would fail
because the messages sending had failed (were not send to the testbinder)
---------

Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>
Co-authored-by: HARPER Jon <jon.harper87@gmail.com>