Disable reactive elasticsearch client which fails (#114)
at startup:
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'localhost:9200' not reachable. Cluster state is offline.
Caused by: org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'localhost:9200' not reachable. Cluster state is offline.
	at org.springframework.data.elasticsearch.client.reactive.SingleNodeHostProvider.lambda$lookupActiveHost$4(SingleNodeHostProvider.java:109) ~[spring-data-elasticsearch-4.1.9.jar:4.1.9]

at every healthcheck:
2021-10-01 08:13:41.037  WARN 1 --- [or-http-epoll-4] a.e.ElasticsearchReactiveHealthIndicator : Elasticsearch health check failed
org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'localhost:9200' not reachable. Cluster state is offline.

Signed-off-by: HARPER Jon <jon.harper87@gmail.com>